#cloud-config

# Above line is not a comment, it is required for cloud-config to run, it is similar to a shebang line in bash!

# Run all the config commands
runcmd:
# Make testfile to see cloud-init started
  - sudo touch /home/ubuntu/test.txt
# Update apt packages
  - sudo apt-get update
# Install webhook
  - cd /home/ubuntu
  - sudo apt-get install webhook
  - sudo curl -fsSL https://raw.githubusercontent.com/csotiistvan/Docker-redeploy-with-webhooks/main/hooks.json > hooks.json
# Docker
  - sudo curl -fsSL https://get.docker.com | sudo sh
  - sudo curl -fsSL https://raw.githubusercontent.com/csotiistvan/Docker-redeploy-with-webhooks/main/rejava.sh > redeploy.sh
  - sudo chmod 777 redeploy.sh
  - sudo chown ubuntu:ubuntu redeploy.sh
#Initial setup only
  - sudo apt install -y postgresql postgresql-contrib
  - export PGPASSWORD="verysafepassword"
  - sudo curl -fsSL https://raw.githubusercontent.com/csotiistvan/Docker-redeploy-with-webhooks/main/create_db.sql > create_db.sql
#  - psql -h terraform-20221130164814864800000001.cblyp46gzosz.eu-central-1.rds.amazonaws.com -p 5432 -U dbadmin -d newimagedb -a -q -f /home/ubuntu/create_db.sql
# Kill any process hogging our ports 
  - sudo kill -9 `sudo lsof -t -i:9000`
  - sudo kill -9 `sudo lsof -t -i:5432`
# Start JAR container
  - sudo docker pull jutsz/jar:latest
  - sudo docker run -d --name=JARJAR -p 80:8080 jutsz/jar:latest
# Start webhook
  - sudo webhook -hooks /home/ubuntu/hooks.json -hotreload -nopanic &
# Redeploy webhook is: http://3.66.103.135:9000/hooks/redeploy
# Cron job to start services at startup and auto-redeploy every 5 minutes IF there is a new release
  - sudo curl -fsSL https://raw.githubusercontent.com/csotiistvan/Docker-redeploy-with-webhooks/main/setupcron.sh | sudo sh
# Create file to denote script run is finished
  - sudo touch /home/ubuntu/java_ready.csv

#For reference
#Interactive docker sesh
#sudo docker exec -it JARJAR /bin/bash
#docker run -it --entrypoint bash ashcroftt/jar:latestest
#docker run -it -p 80:8080 --entrypoint bash jutsz/jar:latest
#java -jar "/home/ubuntu/fileshare.jar"
#java -jar "/opt/app/fileshare.jar"
#curl -fsSL https://raw.githubusercontent.com/csotiistvan/Docker-redeploy-with-webhooks/main/.env > .env
#psql -h terraform-20221130164814864800000001.cblyp46gzosz.eu-central-1.rds.amazonaws.com -p 5432 -U dbadmin newimagedb
#export $(grep -v '^#' .env | xargs)