#cloud-config

# Above line is not a comment, it is required for cloud-config to run, it is similar to a shebang line in bash!

# Run all the config commands
runcmd:
# Make testfile to see cloud-init started
  - sudo touch /home/ubuntu/test.txt
# Update apt packages
  - sudo apt-get update
# Install all dependencies
  - sudo apt install -y default-jre
  - sudo apt install -y default-jdk



# Create file to denote script run is finished
  - sudo touch /home/ubuntu/java_ready.csv