#cloud-config

# Above line is not a comment, it is required for cloud-config to run, it is similar to a shebang line in bash!

# Run all the config commands
runcmd:
# Make testfile to see cloud-init started
  - sudo touch /home/ubuntu/test.txt
# Update apt packages
  - sudo apt-get update
# Install all dependencies
  - sudo apt install -y default-jre
#  - sudo apt install -y default-jdk
# Setup docker
# Install webhook
  - cd /home/ubuntu
  - sudo apt-get install webhook
  - sudo curl -fsSL https://raw.githubusercontent.com/csotiistvan/Docker-redeploy-with-webhooks/main/hooks.json > hooks.json
# Docker
  - sudo curl -fsSL https://get.docker.com | sudo sh
  - sudo curl -fsSL https://raw.githubusercontent.com/csotiistvan/Docker-redeploy-with-webhooks/main/rejava.sh > redeploy.sh
  - sudo chmod 777 redeploy.sh
  - sudo chown ubuntu:ubuntu redeploy.sh
#Initial setup only
  - sudo apt install -y postgresql postgresql-contrib
  - export PGPASSWORD="verysafepassword"
  #- export PGPASSWORD="${{ secrets.PHPASSWD }}"
  - sudo curl -fsSL https://raw.githubusercontent.com/csotiistvan/Docker-redeploy-with-webhooks/main/create_db.sql > create_db.sql
  - psql -h terraform-20221130164814864800000001.cblyp46gzosz.eu-central-1.rds.amazonaws.com -p 5432 -U dbadmin -d newimagedb -a -q -f /home/ubuntu/create_db.sql
# Kill any process hogging our ports 
  - sudo kill -9 `sudo lsof -t -i:9000`
  - sudo kill -9 `sudo lsof -t -i:5432`
# Start JAR container
  - sudo docker pull jutsz/jar:latest
  - sudo docker run -d --name=JARJAR -p 80:8080 -p 5432:5432 jutsz/jar:latest
# Start webhook
  - sudo webhook -hooks hooks.json -verbose
# Create file to denote script run is finished
  - sudo touch /home/ubuntu/java_ready.csv
# Cron job to auto-redeploy every 5 minutes IF there is a new release
  - (sudo crontab -l ; echo "*/5 * * * * sudo bash /home/ubuntu/redeploy.sh ") | crontab -
#For reference
#Interactive docker sesh
#sudo docker exec -it JARJAR /bin/bash
#docker run -it --entrypoint bash ashcroftt/jar:latestest
#docker run -it -p 80:8080 -p 5432:5432 --entrypoint bash jutsz/jar:latest
#java -jar "/home/ubuntu/fileshare.jar"
#java -jar "/opt/app/fileshare.jar"
#psql -h terraform-20221130164814864800000001.cblyp46gzosz.eu-central-1.rds.amazonaws.com -p 5432 -U dbadmin newimagedb
