#cloud-config

# Above line is not a comment, it is required for cloud-config to run, it is similar to a shebang line in bash!

# Run all the config commands
runcmd:
# Update apt packages
  - sudo apt-get update
# Install webhook
  - cd /home/ubuntu
  - sudo apt-get install webhook
  - sudo curl -fsSL https://raw.githubusercontent.com/csotiistvan/Docker-redeploy-with-webhooks/main/hooks.json > hooks.json
# Docker
  - sudo curl -fsSL https://get.docker.com | sudo sh
  - sudo curl -fsSL https://raw.githubusercontent.com/csotiistvan/Docker-redeploy-with-webhooks/main/redeploy.sh > redeploy.sh
  - sudo chmod 777 redeploy.sh
  - sudo chown ubuntu:ubuntu redeploy.sh
  - sudo docker pull hordodonga/web:latest
  - sudo docker run -d --name=APACHE -p 80:80 hordodonga/web:latest
# Kill any process hogging port 9000
  - sudo kill -9 `sudo lsof -t -i:9000`
# Start webhook
  - sudo webhook -hooks /home/ubuntu/hooks.json -hotreload -nopanic &
# Redeploy webhook is: http://0.0.0.0:9000/hooks/redeploy change this when new elastic ip available
# Cron job to auto-redeploy every 4-8 minutes IF there is a new release
# Cron job to start services at startup and auto-redeploy every 5 minutes IF there is a new release
  - sudo curl -fsSL https://raw.githubusercontent.com/csotiistvan/Docker-redeploy-with-webhooks/main/setupcron.sh > setupcron.sh
  - sudo chmod 777 setupcron.sh
  - sudo chown ubuntu:ubuntu setupcron.sh
  - sudo setupcron.sh
# Create file to denote script run is finished
  - sudo touch /home/ubuntu/apache_ready.csv

#For reference
  # - sudo docker pull ashcroftt/nginx-test-artwrks:latest
  # - sudo docker run -d --name=SRV_CONTAINER -p 80:80 ashcroftt/nginx-test-artwrks:main
# Install all dependencies
  # - sudo apt install -y apache2
  # - cd /var/www
  # - sudo echo "hello terraform Apache" >> index.html
  # - sudo cp index.html html/index.html
  # - cd /etc/apache2
  # - sudo sed -i 's/80/42069/' ports.conf
  # - sudo systemctl reload apache2
